baseURL: 'https://2022.ubucon.asia/'
languageCode: en-us
title: UbuCon Asia 2022
theme: ubuconasia
Paginate: 5
buildFuture: true
enableRobotsTXT: true

defaultContentLanguage: en
languages:
  ko:
    languageName: 한국어
    title: 우부콘 아시아 2022
    weight: 2
    params:
      description: >-
        한국에서 열리는 첫 오프라인 우분투 아시아 컨퍼런스.
      period: 2022년 11월 26일 ~ 27일 | 서울 상암동 누리꿈스퀘어
    menu:
      main:
        - identifier: about
          name: 소개
          url: about
          weight: 1
        - identifier: venue-travel-group
          name: 행사장 및 여행정보
          url: venue-and-travel
          weight: 2
        - identifier: venue
          parent: venue-travel-group
          name: 행사장
          url: venue-and-travel/venue
          weight: 2
        - identifier: programs-group
          name: 프로그램
          url: programs
          weight: 3
        - identifier: sessions
          parent: programs-group
          name: 세션
          url: sessions
          weight: 3
        - identifier: confirmed
          parent: programs-group
          name: 참여 확인된 세션
          url: confirmed
          weight: 3
        - identifier: sponsors-group
          name: 후원사/개인후원
          url: sponsors
          weight: 4
        - identifier: sponsors
          parent: sponsors-group
          name: 후원사
          url: sponsors
          weight: 4
        - identifier: patrons
          parent: sponsors-group
          name: 개인 후원자
          url: patrons
          weight: 4
        - identifier: news
          name: 소식
          url: news
          weight: 5
        - identifier: wiki
          name: 위키
          url: https://wiki.ubuntu.com/UbuconAsia/2022
          weight: 6
  en:
    languageName: English
    title: UbuCon Asia 2022
    weight: 1
    params:
      description: >-
        The first In-person Ubuntu Asia conference in South Korea.
      period: November 26th ~ 27th, 2022 | Nuritkum Square, Seoul, South Korea
    menu:
      main:
        - identifier: about
          name: About
          url: about
          weight: 1
        - identifier: venue-travel-group
          name: Venue & Travel
          url: venue-and-travel
          weight: 2
        - identifier: venue
          parent: venue-travel-group
          name: Venue
          url: venue-and-travel/venue
          weight: 2
        - identifier: programs-group
          name: Programs
          url: programs
          weight: 3
        - identifier: sessions
          parent: programs-group
          name: Sessions
          url: sessions
          weight: 3
        - identifier: confirmed
          parent: programs-group
          name: Confirmed sessions
          url: confirmed
          weight: 3
        - identifier: sponsors-group
          name: Sponsors/Patrons
          url: sponsors
          weight: 4
        - identifier: sponsors
          parent: sponsors-group
          name: Sponsors
          url: sponsors
          weight: 4
        - identifier: patrons
          parent: sponsors-group
          name: Individual patrons
          url: patrons
          weight: 4
        - identifier: news
          name: News
          url: news
          weight: 5
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2022
          weight: 6
  id:
    languageName: Bahasa Indonesia
    title: UbuCon Asia 2022
    weight: 2
    params:
      description: >-
        The first In-person Ubuntu Asia conference in South Korea.
      period: November 26th ~ 27th, 2022 | Nuritkum Square, Seoul, South Korea
    menu:
      main:
        - identifier: about
          name: Tentang
          url: about
          weight: 1
        - identifier: venue-travel-group
          name: Venue & Travel
          url: venue-and-travel
          weight: 2
        - identifier: venue
          parent: venue-travel-group
          name: Venue
          url: venue-and-travel/venue
          weight: 2
        - identifier: programs-group
          name: Program
          url: programs
          weight: 3
        - identifier: sessions
          parent: programs-group
          name: Sesi
          url: sessions
          weight: 3
        - identifier: confirmed
          parent: programs-group
          name: Sesi yang Dikonfirmasi
          url: confirmed
          weight: 3
        - identifier: sponsors-group
          name: Sponsor/Patron
          url: sponsors
          weight: 4
        - identifier: sponsors
          parent: sponsors-group
          name: Sponsor
          url: sponsors
          weight: 4
        - identifier: patrons
          parent: sponsors-group
          name: Patron Individual
          url: patrons
          weight: 4
        - identifier: news
          name: Berita
          url: news
          weight: 5
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2022
          weight: 6
  ja:
    languageName: 日本語
    title: UbuCon Asia 2022
    weight: 3
    params:
      description: >-
        The first In-person Ubuntu Asia conference in South Korea.
      period: November 26th ~ 27th, 2022 | Nuritkum Square, Seoul, South Korea
    menu:
      main:
        - identifier: about
          name: Ubucon Asiaとは
          url: about
          weight: 1
        - identifier: venue-travel-group
          name: Venue & Travel
          url: venue-and-travel
          weight: 2
        - identifier: venue
          parent: venue-travel-group
          name: Venue
          url: venue-and-travel/venue
          weight: 2
        - identifier: programs-group
          name: Programs
          url: programs
          weight: 3
        - identifier: sessions
          parent: programs-group
          name: セッション
          url: sessions
          weight: 3
        - identifier: confirmed
          parent: programs-group
          name: Confirmed sessions
          url: confirmed
          weight: 3
        - identifier: sponsors-group
          name: スポンサー/Patrons
          url: sponsors
          weight: 4
        - identifier: sponsors
          parent: sponsors-group
          name: スポンサー
          url: sponsors
          weight: 4
        - identifier: patrons
          parent: sponsors-group
          name: Individual patrons
          url: patrons
          weight: 4
        - identifier: news
          name: ニュース
          url: news
          weight: 4
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2022
          weight: 5
  zh-hant-tw:
    languageName: 正體中文(臺灣)
    title: UbuCon Asia 2022
    weight: 2
    params:
      description: >-
        The first In-person Ubuntu Asia conference in South Korea.
      period: November 26th ~ 27th, 2022 | Nuritkum Square, Seoul, South Korea
    menu:
      main:
        - identifier: about
          name: About
          url: about
          weight: 1
        - identifier: venue-travel-group
          name: Venue & Travel
          url: venue-and-travel
          weight: 2
        - identifier: venue
          parent: venue-travel-group
          name: Venue
          url: venue-and-travel/venue
          weight: 2
        - identifier: programs-group
          name: Programs
          url: programs
          weight: 3
        - identifier: sessions
          parent: programs-group
          name: Sessions
          url: sessions
          weight: 3
        - identifier: confirmed
          parent: programs-group
          name: Confirmed sessions
          url: confirmed
          weight: 3
        - identifier: sponsors-group
          name: Sponsors/Patrons
          url: sponsors
          weight: 4
        - identifier: sponsors
          parent: sponsors-group
          name: Sponsors
          url: sponsors
          weight: 4
        - identifier: patrons
          parent: sponsors-group
          name: Individual patrons
          url: patrons
          weight: 4
        - identifier: news
          name: News
          url: news
          weight: 5
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2022
          weight: 6
  zh-hans-cn:
    language-name: 简体中文（中国大陆）
    title: UbuCon Asia 2022
    weight: 3
    params:
      description: >-
        首次在韩国举行的 Ubuntu 亚洲峰会。
      period: 2022 年 11 月 26 至 27 日  | 韩国，首尔市，Nuritkum 广场
    menu:
      main:
        - identifier: about
          name: 关于 Ubucon Asia
          url: about
          weight: 1
        - identifier: venue-travel-group
          name: 场馆与旅行
          url: venue-and-travel
          weight: 2
        - identifier: venue
          parent: venue-travel-group
          name: 场馆
          url: venue-and-travel/venue
          weight: 2
        - identifier: programs-group
          name: 会议
          url: programs
          weight: 3
        - identifier: sessions
          parent: programs-group
          name: 会议流程
          url: sessions
          weight: 3
        - identifier: confirmed
          parent: programs-group
          name: 会议流程（已确认）
          url: confirmed
          weight: 3
        - identifier: sponsors-group
          name: 赞助商
          url: sponsors
          weight: 4
        - identifier: sponsors
          parent: sponsors-group
          name: 赞助商
          url: sponsors
          weight: 4
        - identifier: patrons
          parent: sponsors-group
          name: 个人赞助者
          url: patrons
          weight: 4
        - identifier: news
          name: 新闻
          url: news
          weight: 4
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2022
          weight: 5
params:
  contact: contact@ubucon.asia
  calendarOrganizer: UbuCon Asia 2022 Organizers
  calendarUidSuffix: 2022.asia.ubucon.org
  facebook: ubuconasia
  twitter: ubuconasia
  github: ubucon-asia
  repo: https://github.com/ubucon-asia/2022
  copyright:  >-
    © 2022 UbuCon Asia 2022 Website authors.
    Except where otherwise noted, Website source code licensed under MIT, Contents licensed under CC BY 4.0. 
    Ubuntu and Canonical are registered trademarks of Canonical Ltd.
  email: contact@ubucon.asia
  registerURLs:
    attendee: https://eventyay.com/e/75ac7f83
    callForSpeakers: /cfs
  timetable:
    dateStart: 2022-11-26T12:00:00+09:00
    dateEnd: 2022-11-27T22:00:00+09:00
    timeStart: 2000-01-01T13:00:00+09:00 # Use random date for timeStart param
outputs:
  home: ["HTML", "RSS", "Calendar", "JSON"]
markup:
  goldmark:
    renderer:
      unsafe: true